Name:           ros-kinetic-capabilities
Version:        0.2.0
Release:        0%{?dist}
Summary:        ROS capabilities package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/capabilities
Source0:        %{name}-%{version}.tar.gz

Requires:       PyYAML
Requires:       ros-kinetic-bondpy
Requires:       ros-kinetic-message-runtime
Requires:       ros-kinetic-nodelet
Requires:       ros-kinetic-roslaunch
Requires:       ros-kinetic-rospy
Requires:       ros-kinetic-std-msgs
Requires:       ros-kinetic-std-srvs
BuildRequires:  python-coverage
BuildRequires:  python-mock
BuildRequires:  python-pep8
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-geometry-msgs
BuildRequires:  ros-kinetic-message-generation
BuildRequires:  ros-kinetic-roslaunch
BuildRequires:  ros-kinetic-rospy
BuildRequires:  ros-kinetic-rosservice
BuildRequires:  ros-kinetic-rostest
BuildRequires:  ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-std-srvs

%description
Package which implements capabilities, including code to parse capability
interface specs, to parse capability provider specs, and implement the
capability server.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed May 04 2016 William Woodall <william@osrfoundation.org> - 0.2.0-0
- Autogenerated by Bloom

